---
AWSTemplateFormatVersion: "2010-09-09"

Description: Single-instance web server
Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - m1.medium
    Description: Instance type
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Where the instance will be placed
  IamInstanceProfile:
    Type: String
    Description: EC2 instance SSM role

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo amazon-linux-extras install nginx1 -y
          sudo service nginx start
      ImageId: ami-01216e7612243e0ef
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Ref: SecurityGroup
      SubnetId:
        Ref: Subnet
      IamInstanceProfile:
        Ref: IamInstanceProfile